preset: recommended
risky: true
finder:
  name: "*.php"
enabled:
  - not_operator_with_successor_space
  - const_separation
  - no_extra_block_blank_lines
  - phpdoc_annotation_without_dot
  - phpdoc_no_empty_return
  - property_separation
  - align_equals
  - concat_with_spaces
disabled:
  - unalign_equals
  - concat_without_spaces
